# Generated by Django 5.2.9 on 2025-12-29 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание заказа')),
                ('order_type', models.CharField(choices=[('corpus', 'Корпусная мебель'), ('upholstered', 'Мягкая мебель')], max_length=20, verbose_name='Тип мебели')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цеха')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Начальник цеха')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО рабочего')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.workshop', verbose_name='Цех')),
            ],
        ),
        migrations.CreateModel(
            name='OrderWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.order')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.workshop')),
            ],
            options={
                'verbose_name': 'Цех в заказе',
                'verbose_name_plural': 'Цеха в заказах',
                'unique_together': {('order', 'workshop')},
            },
        ),
    ]
